server:
  port: 19100

spring:
  application:
    name: mcp-webflux-client
  main:
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY:sk-9c7fc48608a448c5987dc99b8fea1271}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        sse:
          connections:
            server1:
              url: http://192.168.10.142:38080/mcp/simple
              sse-endpoint: /sse
            server2:
              url: http://192.168.10.142:38080/gateway/gateWayDeviceStatus
              sse-endpoint: /sse
#            server1:
#              url: http://localhost:19000 # 本地
#            server2:
#              url: https://mcp.amap.com?key=xxx # 远程高德MCP服务