server:
  port: 8080

spring:
  application:
    name: alibaba-chat

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-e53af0e5980a47e2bcad62ea226f9d5e}
      chat:
        options:
          model: qwen-max