server:
  port: 8080

spring:
  application:
    name: alibaba-chat

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:sk-9c7fc48608a448c5987dc99b8fea1271}
      chat:
        options:
          model: qwen-max