server:
  port: 8080

spring:
  application:
    name: vector-simple

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY:sk-e53af0e5980a47e2bcad62ea226f9d5e}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v1