server:
  port: 21001

spring:
  application:
    name: dosp-mcp-server
  ai:
    mcp:
      server:
        name: dospMcpServer
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "mcp服务提供"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
#    alibaba:
#      mcp:
#        nacos:
#          namespace: dosp-dev
#          server-addr: 192.168.20.187:18848
#          username: nacos
#          password: nacos
#          registry:
#            enabled: true
#            service-group: flw
#            service-name: dospMcp

#SERVER: http://127.0.0.1:8090
SERVER: https://dosp.senterxljk.com.cn:19200/dosp-api
#SERVER: http://192.168.20.187:906/dosp-api
SERVER_FIGURE: http://192.168.20.90:8085/api/v0/generate_plotly_figure_v2