server:
  port: 20100

spring:
  application:
    name: mcp-stdio-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json