server:
  port: 20100

spring:
  application:
    name: mcp-stdio-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        stdio:
          connections:
            server1:
              command: java
              args:
                - -jar
                - /Users/guotao/IdeaProjects/spring-ai-tutorial/mcp/server/mcp-stdio-server/target/mcp-stdio-server-1.0-SNAPSHOT.jar
                - --port=20000
                - --mode=production
#        stdio:
#          servers-configuration: classpath:mcp-servers.json