spring:
  application:
    name: mcp-nacos3-client
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications

    alibaba:
      mcp:
        nacos:
          service-namespace: 4ad3108b-4d44-43d0-9634-3c1ac4850c8c
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          client:
            enabled: true
            sse:
              connections:
                server1:
                  service-name: webflux-mcp-server
                  version: 1.0.0

#          enabled: true
#          server-addr: 127.0.0.1:8848
#          username: nacos
#          password: nacos
#
#          client:
#            nacos-enabled: true
#            sse:
#              connections:
#                server1:
#                  service-namespace: 9ba5f1aa-b37d-493b-9057-72918a40ef35
#                  service-group: mcp-server
#                  service-name: webflux-mcp-server
