server:
  port: 8080

spring:
  application:
    name: vector-redis

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v1

    vectorstore:
      redis:
        initialize-schema: true
        prefix: prefix_yingzi_
        index-name: index_yingzi_

  data:
    redis:
      host: localhost
      port: 6379 # Redis服务器连接端口