server:
  port: 8080

spring:
  application:
    name: tool-calling

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY:sk-e53af0e5980a47e2bcad62ea226f9d5e}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max

    toolcalling:
      time:
        enabled: true
      weather:
        enabled: true
        api-key: ${WEATHER_API_KEY}