server:
  port: 8080

spring:
  application:
    name: structured-output

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY:sk-9c7fc48608a448c5987dc99b8fea1271}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max